### ISSUE TITLE
verify/credentials should return 201

### ISSUE THREAD

**Issue by OR13** [transmute-industries/vc.transmute.world#56]
This endpoint: https://vc.transmute.world/v0.1.0/verify/credentials should be returning 201. It returns 200. That is causing it to fail the vc-http-api test. The spec states 201 https://w3c-ccg.github.io/vc-http-api/

**Comment by aljones15** [comment]
just so you know particular this test: https://github.com/w3c-ccg/vc-http-api/blob/1a32f8e19ba6bfb92c72c63cf7e9ea09b280fc58/packages/vc-http-api-test-server/__tests__/issueCredential.spec.js#L15-L23

**Comment by gjgd** [comment]
https://github.com/transmute-industries/vc.transmute.world/pull/57
